config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true

  validates :rating, inclusion: { in: 1..5 }, allow_nil: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @average_rating = @restaurant.reviews.average(:rating).to_f
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.rating = params[:review][:rating].to_i
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# stylesheets %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="background-container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ["Chinese", "Italian", "Japanese", "French", "Belgian"], include_blank: "Select a category" %>
  <%= f.submit "Add Restaurant", class: "btn btn-secondary" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>My Yelp Clone</h1>

<div class="restaurants-list">
    <div class="custom-link-to">
      <%= link_to new_restaurant_path do %>
      <i class="fa-solid fa-plus" style="color: #969aa2;"></i>
      Add restaurant
      <% end %>
    </div>
  <hr>
  <ul class="list-group list-unstyled">
    <% @restaurants.each do |restaurant| %>
      <li class= "mb-3">
        <div class="card-restaurant">
          <img src="<%= image_path('food.jpg') %>" />
          <div class="card-restaurant-infos">
            <h2><%= restaurant.name %></h2>
            <p><%= restaurant.category %></p>
            <p><%= restaurant.address %></p>
            <p><%= restaurant.phone_number %></p>
            <p><%= link_to "See details", restaurant_path(restaurant) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>

<%= render 'form' %>

<div class="custom-link-to">
  <%= link_to restaurants_path do %>
    <i class="fa-solid fa-rotate-left" style="color: #8a8e93;"></i>
    Back to all restaurants
  <% end %>
</div>

app/views/restaurants/show.html.erb
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <h1>Restaurant <%= @restaurant.name %></h1>
  </div>

  <div class="mt-2">
    <h2>Average Rating: <%= number_with_precision(@average_rating, precision: 1) %> / 5</h2>
    <p>Located in: <%= @restaurant.address %></p>
    <p>Speciality: <%= @restaurant.category %></p>
    <p>Contact: <%= @restaurant.phone_number %> </p>
  </div>

  <hr>

  <h2>Write a review ✍️</h2>
  <%# add rating input %>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content, class: "form-control" %>
    <%= f.input :rating, collection: [1, 2, 3, 4, 5], include_blank: "Select a score" %>
    <%= f.submit "+ Add review", class:"btn btn-secondary" %>
  <% end %>

  <hr>

  <%# display average rating %>
  <h2>Reviews</h2>


  <div class="mt-2">
    <ul class="list-group">
      <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item mb-3">

          <div class="d-flex justify-content-between">
            <h2>Rating: <%= review.rating %> / 5 </h2>
            <%= link_to review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <i class="fa-solid fa-trash" style="color: #898d94;"></i>
            <% end  %>
          </div>

          <div>
            <%= review.content %>
          </div>

        </li>
      <% end %>
    </ul>
  </div>

  <hr>

  <div class="custom-link-to">
    <%= link_to restaurants_path do %>
      <i class="fa-solid fa-rotate-left" style="color: #8a8e93;"></i>
      Back to all restaurants
    <% end %>
  |
    <%= link_to restaurant_path(@restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
      <i class="fa-solid fa-trash" style="color: #898d94;"></i>
      Delete restaurant
    <% end  %>
  </div>